## Created by nov 05 on 2026-03-26
## Run the following commands to generate "kubernetes-config.yaml" 
## before deploying the app by running "kubectl apply -f kubernetes-config.yaml".
#
# export PROJECT_ID=$DEVSHELL_PROJECT_ID
# # Enable the orgpolicy API non-interactively
# yes | gcloud services enable orgpolicy.googleapis.com --project=$PROJECT_ID --quiet
#
# # Detect allowed region dynamically
# export ALLOWED_REGION=$(gcloud org-policies describe constraints/gcp.resourceLocations \
#   --project=$PROJECT_ID \
#   --flatten="spec.rules[].values.allowedValues[]" \
#   --format="value(spec.rules.values.allowedValues)" \
#   | grep -oP '(?<=in:)(us|europe)[a-z0-9-]+(?=-locations)' \
#   | head -n1
# )
#
# envsubst < kubernetes-config-template.yaml > kubernetes-config.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  labels:
    app: devops
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
      tier: frontend
  template:
    metadata:
      labels:
        app: devops
        tier: frontend
    spec:
      containers:
      - name: devops-demo
        # Update your image path here
        # image: us-east4-docker.pkg.dev/qwiklabs-gcp-01-4c781bfff05d/devops-demo/devops-image:v0.2
        image: ${ALLOWED_REGION}-docker.pkg.dev/${PROJECT_ID}/devops-demo/devops-image:v0.2
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: devops-deployment-lb
  labels:
    app: devops
    tier: frontend-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: devops
    tier: frontend
